# Generated by Django 4.2 on 2023-04-21 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='groups',
            field=models.ManyToManyField(to='api.group'),
        ),
    ]
