# Generated by Django 4.2 on 2023-04-21 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_channel_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='groups',
        ),
    ]
